name: Pruebas de conexi贸n con base de datos Neon

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prueba-base-datos:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4
      
      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary python-dotenv numpy
          
      - name: Ejecutar pruebas de conexi贸n
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: |
          echo "Iniciando pruebas de conexi贸n a Neon PostgreSQL..."
          python test_neon.py
          
      - name: Verificar resultados
        if: always()
        run: |
          echo "Pruebas completadas - revisar logs arriba"
