name: Ejecutar modelo de validación de firmas

on:  
  push:  
    branches:  
      - main  
  workflow_dispatch:  

jobs:  
  run-model:
    runs-on: ubuntu-latest  
    steps:
      - name: Clonar repositorio  
        uses: actions/checkout@v4 

      - name: Configurar Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: "3.11"  

      - name: Instalar dependencias  
        run: |  
          pip install --upgrade pip  
          pip install -r requerimientos.txt  

      - name: Ejecutar el modelo  
        run: python modelo.py  
