name: Ejecutar Modelo

on:
  push:
    branches:
      - main

jobs:
  run-model:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar el modelo
        run: python modelo.py | tee resultado.txt

      - name: Subir logs de ejecución
        uses: actions/upload-artifact@v3
        with:
          name: resultado-ejecucion
          path: resultado.txt
