name: Test prediction

on:
  push:
    branches: [API]
  pull_request:
    branches: [API]
  workflow_dispatch:

jobs: 
  test-api:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.linkbd }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn requests tensorflow pillow psycopg2 supabase python-multipart

      - name: Run FastAPI app in background
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Correr prueba de API
        run: |
          curl -X POST "http://localhost:8000/predict/image/" \
          -H "accept: application/json" \
          -H "Content-Type: multipart/form-data" \
          -F "archivo=@prueba.png" \
          -o result.json
    
      - name: Print prediction result
        run: cat result.json
